const availableCities = [
  'New York',
  'Los Angeles',
  'Chicago',
  'Houston',
  'Phoenix',
  'Philadelphia',
  'San Antonio',
  'San Diego',
  'Dallas',
  'San Jose',
  'Austin',
  'Jacksonville',
  'Fort Worth',
  'Columbus',
  'Charlotte',
  'San Francisco',
  'Indianapolis',
  'Seattle',
  'Denver',
  'Washington',
  'Boston',
  'El Paso',
  'Nashville',
  'Detroit',
  'Oklahoma City',
  'Portland',
  'Las Vegas',
  'Memphis',
  'Louisville',
  'Baltimore',
  'Milwaukee',
  'Albuquerque',
  'Tucson',
  'Fresno',
  'Sacramento',
  'Kansas City',
  'Long Beach',
  'Mesa',
  'Atlanta',
  'Colorado Springs',
  'Virginia Beach',

  'São Paulo',
  'Rio de Janeiro',
  'Brasília',
  'Salvador',
  'Fortaleza',
  'Belo Horizonte',
  'Manaus',
  'Curitiba',
  'Recife',
  'Goiânia',
  'Belém',
  'Porto Alegre',
  'Guarulhos',
  'Campinas',
  'São Luís',
  'São Gonçalo',
  'Maceió',
  'Duque de Caxias',
  'Natal',
  'Teresina',
  'São Bernardo do Campo',
  'Campo Grande',
  'Jaboatão dos Guararapes',

  'London',
  'Berlin',
  'Madrid',
  'Rome',
  'Paris',
  'Bucharest',
  'Vienna',
  'Hamburg',
  'Warsaw',
  'Budapest',
  'Barcelona',
  'Munich',
  'Milan',
  'Prague',
  'Sofia',
  'Brussels',
  'Amsterdam',
  'Copenhagen',
  'Dublin',
  'Lisbon',
  'Athens',
  'Stockholm',
  'Oslo',
  'Helsinki',
  'Zurich',
  'Manchester',
  'Edinburgh',
  'Glasgow',
  'Liverpool',
  'Birmingham',

  'Tokyo',
  'Delhi',
  'Shanghai',
  'Mumbai',
  'Beijing',
  'Osaka',
  'Karachi',
  'Chongqing',
  'Istanbul',
  'Dhaka',
  'Manila',
  'Tianjin',
  'Moscow',
  'Shenzhen',
  'Guangzhou',
  'Jakarta',
  'Lahore',
  'Seoul',
  'Chennai',
  'Bangalore',
  'Kolkata',
  'Bangkok',
  'Hong Kong',
  'Singapore',
  'Taipei',
  'Riyadh',
  'Dubai',
  'Abu Dhabi',
  'Doha',
  'Kuala Lumpur',

  'Cairo',
  'Lagos',
  'Kinshasa',
  'Johannesburg',
  'Luanda',
  'Dar es Salaam',
  'Khartoum',
  'Abidjan',
  'Alexandria',
  'Addis Ababa',
  'Nairobi',
  'Cape Town',
  'Durban',
  'Casablanca',
  'Accra',
  'Algiers',
  'Kano',
  'Ibadan',
  'Dakar',
  'Pretoria',

  'Sydney',
  'Melbourne',
  'Brisbane',
  'Perth',
  'Adelaide',
  'Gold Coast',
  'Auckland',
  'Wellington',
  'Christchurch',
  'Suva',
  'Port Moresby',
  'Honolulu'
];

export const topCities = [
  'New York',
  'London',
  'Tokyo',
  'Paris',
  'Sydney',
  'Berlin',
  'Rome',
  'Madrid',
  'Moscow',
  'Beijing',
  'Shanghai',
  'Dubai',
  'Singapore',
  'Seoul',
  'Mumbai',
  'Delhi',
  'Bangkok',
  'Hong Kong',
  'Toronto',
  'Los Angeles',
  'Chicago',
  'Miami',
  'São Paulo',
  'Rio de Janeiro',
  'Buenos Aires',
  'Lima',
  'Mexico City',
  'Cairo',
  'Johannesburg',
  'Cape Town',
  'Nairobi',
  'Lagos',
  'Istanbul',
  'Athens',
  'Amsterdam',
  'Vienna',
  'Prague',
  'Warsaw',
  'Stockholm',
  'Oslo',
  'Copenhagen',
  'Helsinki',
  'Dublin',
  'Lisbon',
  'Brussels',
  'Zurich',
  'Vancouver',
  'Montreal',
  'San Francisco'
];

const colorOptions = [
  { value: '#3b82f6', name: 'Blue', bg: 'bg-blue-500' },
  { value: '#ef4444', name: 'Red', bg: 'bg-red-500' },
  { value: '#10b981', name: 'Green', bg: 'bg-green-500' },
  { value: '#f59e0b', name: 'Orange', bg: 'bg-orange-500' },
  { value: '#8b5cf6', name: 'Purple', bg: 'bg-purple-500' },
  { value: '#ec4899', name: 'Pink', bg: 'bg-pink-500' }
];

const monthNames = [
  'Jan',
  'Feb',
  'Mar',
  'Apr',
  'May',
  'Jun',
  'Jul',
  'Aug',
  'Sep',
  'Oct',
  'Nov',
  'Dec'
];

export { availableCities, colorOptions, monthNames };
